const character_list = [
  {
    id: "1",
    imgUrl: "./img/character/list/character-list-thum-1.jpg",
    personUrl: "./img/character/img_person/kansong/01.png",
    kName: "월하정인",
    cName: "月下情人",
    useColor1: "",
    useColor2: "",
    useColor3: "",
    relicImgUrl: "./img/character/relic/kansong/01.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/wolhajeongin/",
  },
  {
    id: "2",
    imgUrl: "./img/character/list/character-list-thum-2.jpg",
    personUrl: "./img/character/img_person/kansong/02.png",
    kName: "백매고기",
    cName: "白梅古器",
    useColor1: "./img/character/usecolor/kansong/02-1.jpg",
    useColor2: "./img/character/usecolor/kansong/02-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/kansong/02.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/baekmaegogi/",
  },
  {
    id: "3",
    imgUrl: "./img/character/list/character-list-thum-3.jpg",
    personUrl: "./img/character/img_person/kansong/03.png",
    kName: "불수앵무",
    cName: "佛手鸚鵡",
    useColor1: "./img/character/usecolor/kansong/03-1.jpg",
    useColor2: "./img/character/usecolor/kansong/03-1.jpg",
    useColor3: "./img/character/usecolor/kansong/03-3.jpg",
    relicImgUrl: "./img/character/relic/kansong/03.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/bulsuaengmu/",
  },
  {
    id: "4",
    imgUrl: "./img/character/list/character-list-thum-4.jpg",
    personUrl: "./img/character/img_person/kansong/04.png",
    kName: "기명절지",
    cName: "器皿折枝",
    useColor1: "./img/character/usecolor/kansong/04-1.jpg",
    useColor2: "./img/character/usecolor/kansong/04-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/kansong/04.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/gimyeongjeolji/",
  },
  {
    id: "5",
    imgUrl: "./img/character/list/character-list-thum-5.jpg",
    personUrl: "./img/character/img_person/kansong/05.png",
    kName: "오동폐월",
    cName: "梧桐吠月",
    useColor1: "./img/character/usecolor/kansong/05-1.jpg",
    useColor2: "./img/character/usecolor/kansong/05-2.jpg",
    useColor3: "./img/character/usecolor/kansong/05-3.jpg",
    relicImgUrl: "./img/character/relic/kansong/05.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/odongpyewoel/",
  },
  {
    id: "6",
    imgUrl: "./img/character/list/character-list-thum-6.jpg",
    personUrl: "./img/character/img_person/kansong/06.png",
    kName: "황묘농접",
    cName: "黃猫弄蝶",
    useColor1: "./img/character/usecolor/kansong/06-1.jpg",
    useColor2: "./img/character/usecolor/kansong/06-2.jpg",
    useColor3: "./img/character/usecolor/kansong/06-3.jpg",
    relicImgUrl: "./img/character/relic/kansong/06.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/hwangmyonongjeob/",
  },
  {
    id: "7",
    imgUrl: "./img/character/list/character-list-thum-7.jpg",
    personUrl: "./img/character/img_person/kansong/07.png",
    kName: "하화청정",
    cName: "荷畵蜻䗴",
    useColor1: "./img/character/usecolor/kansong/07-1.jpg",
    useColor2: "./img/character/usecolor/kansong/07-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/kansong/07.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/hahwacheongjeong/",
  },
  {
    id: "8",
    imgUrl: "./img/character/list/character-list-thum-8.jpg",
    personUrl: "./img/character/img_person/kansong/08.png",
    kName: "국정추묘",
    cName: "菊庭秋猫",
    useColor1: "./img/character/usecolor/kansong/08-1.jpg",
    useColor2: "./img/character/usecolor/kansong/08-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/kansong/08.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/kukjeongchumyo/",
  },
  {
    id: "9",
    imgUrl: "./img/character/list/character-list-thum-9.jpg",
    personUrl: "./img/character/img_person/kansong/09.png",
    kName: "환원석죽",
    cName: "萱苑石竹",
    useColor1: "./img/character/usecolor/kansong/09-1.jpg",
    useColor2: "./img/character/usecolor/kansong/09-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/kansong/09.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/guibihojeob/",
  },
  {
    id: "10",
    imgUrl: "./img/character/list/character-list-thum-10.jpg",
    personUrl: "./img/character/img_person/kansong/10.png",
    kName: "장미호접",
    cName: "薔薇蝴蝶",
    useColor1: "./img/character/usecolor/kansong/10-1.jpg",
    useColor2: "./img/character/usecolor/kansong/10-2.jpg",
    useColor3: "./img/character/usecolor/kansong/10-3.jpg",
    relicImgUrl: "./img/character/relic/kansong/10.jpg",
    copyrightUrl: "",
    copyrightText: "",
    relicUrl: "http://kansong.org/collection/jangmihojeob/",
  },
  {
    id: "11",
    imgUrl: "./img/character/list/character-list-thum-11.jpg",
    personUrl: "./img/character/img_person/nfm/01.png",
    kName: "후수",
    cName: "後綬",
    useColor1: "./img/character/usecolor/nfm/01-1.jpg",
    useColor2: "./img/character/usecolor/nfm/01-2.jpg",
    useColor3: "./img/character/usecolor/nfm/01-3.jpg",
    relicImgUrl: "./img/character/relic/nfm/01.png",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속001929’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다. ",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100100192900000",
  },
  {
    id: "12",
    imgUrl: "./img/character/list/character-list-thum-12.jpg",
    personUrl: "./img/character/img_person/nfm/02.png",
    kName: "활옷",
    cName: "",
    useColor1: "./img/character/usecolor/nfm/02-1.jpg",
    useColor2: "./img/character/usecolor/nfm/02-2.jpg",
    useColor3: "./img/character/usecolor/nfm/02-3.jpg",
    relicImgUrl: "./img/character/relic/nfm/02.png",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속000971’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100100097100000",
  },
  {
    id: "13",
    imgUrl: "./img/character/list/character-list-thum-13.jpg",
    personUrl: "./img/character/img_person/nfm/03.png",
    kName: "원삼",
    cName: "圓衫",
    useColor1: "./img/character/usecolor/nfm/03-1.jpg",
    useColor2: "./img/character/usecolor/nfm/03-2.jpg",
    useColor3: "./img/character/usecolor/nfm/03-3.jpg",
    relicImgUrl: "./img/character/relic/nfm/03.png",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속070200’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다.  ",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100107020000000",
  },
  {
    id: "14",
    imgUrl: "./img/character/list/character-list-thum-14.jpg",
    personUrl: "./img/character/img_person/nfm/04.png",
    kName: "원삼",
    cName: "圓衫",
    useColor1: "./img/character/usecolor/nfm/04-1.jpg",
    useColor2: "./img/character/usecolor/nfm/04-2.jpg",
    useColor3: "./img/character/usecolor/nfm/04-3.jpg",
    relicImgUrl: "./img/character/relic/nfm/04.png",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속078907’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100107890700000",
  },
  {
    id: "15",
    imgUrl: "./img/character/list/character-list-thum-15.jpg",
    personUrl: "./img/character/img_person/nfm/05.png",
    kName: "두루주머니",
    cName: "",
    useColor1: "./img/character/usecolor/nfm/05-1.jpg",
    useColor2: "./img/character/usecolor/nfm/05-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/nfm/05.jpg",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속070808’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100107080800000",
  },
  {
    id: "16",
    imgUrl: "./img/character/list/character-list-thum-16.jpg",
    personUrl: "./img/character/img_person/nfm/06.png",
    kName: "까치두루마기",
    cName: "",
    useColor1: "./img/character/usecolor/nfm/06-1.jpg",
    useColor2: "./img/character/usecolor/nfm/06-2.jpg",
    useColor3: "./img/character/usecolor/nfm/06-3.jpg",
    relicImgUrl: "./img/character/relic/nfm/06.png",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속005607’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100100560700000",
  },
  {
    id: "17",
    imgUrl: "./img/character/list/character-list-thum-17.jpg",
    personUrl: "./img/character/img_person/nfm/07.png",
    kName: "굴레",
    cName: "",
    useColor1: "./img/character/usecolor/nfm/07-1.jpg",
    useColor2: "./img/character/usecolor/nfm/07-2.jpg",
    useColor3: "./img/character/usecolor/nfm/07-3.jpg",
    relicImgUrl: "./img/character/relic/nfm/07.jpg",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속006274’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100100627400000",
  },
  {
    id: "18",
    imgUrl: "./img/character/list/character-list-thum-18.jpg",
    personUrl: "./img/character/img_person/nfm/08.png",
    kName: "대삼작",
    cName: "大三作",
    useColor1: "./img/character/usecolor/nfm/08-1.jpg",
    useColor2: "./img/character/usecolor/nfm/08-2.jpg",
    useColor3: "./img/character/usecolor/nfm/08-3.jpg",
    relicImgUrl: "./img/character/relic/nfm/08.jpg",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속001028’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100100102800000",
  },
  {
    id: "19",
    imgUrl: "./img/character/list/character-list-thum-19.jpg",
    personUrl: "./img/character/img_person/nfm/09.png",
    kName: "노리개",
    cName: "",
    useColor1: "./img/character/usecolor/nfm/09-1.jpg",
    useColor2: "./img/character/usecolor/nfm/09-2.jpg",
    useColor3: "./img/character/usecolor/nfm/09-3.jpg",
    relicImgUrl: "./img/character/relic/nfm/09.jpg",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속001356’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100100135600000",
  },
  {
    id: "20",
    imgUrl: "./img/character/list/character-list-thum-20.jpg",
    personUrl: "./img/character/img_person/nfm/10.png",
    kName: "당의",
    cName: "唐衣",
    useColor1: "./img/character/usecolor/nfm/10-1.jpg",
    useColor2: "./img/character/usecolor/nfm/10-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/nfm/10.png",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속006151’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100100615100000",
  },
  {
    id: "21",
    imgUrl: "./img/character/list/character-list-thum-21.jpg",
    personUrl: "./img/character/img_person/nfm/11.png",
    kName: "흉배",
    cName: "胸背",
    useColor1: "./img/character/usecolor/nfm/11-1.jpg",
    useColor2: "./img/character/usecolor/nfm/11-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/nfm/11.png",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립민속박물관에서 공공누리 제 1 유형으로 개방한 ‘민속001026’를 이용하였으며, 해당 저작물은 국립민속박물관에서 무료로 다운받을 수 있습니다. ",
    relicUrl: "https://www.nfm.go.kr/user/data/home/101/DataRelicView.do?seq=PS0100200100100102600000",
  },
  {
    id: "22",
    imgUrl: "./img/character/list/character-list-thum-22.jpg",
    personUrl: "./img/character/img_person/gogung/01.png",
    kName: "덕혜옹주 문항라 부금 당의",
    cName: "德惠翁主紋亢羅付金唐衣",
    useColor1: "./img/character/usecolor/gogung/01-1.jpg",
    useColor2: "./img/character/usecolor/gogung/01-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/gogung/01.png",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립고궁박물관에서 공공누리 제 1 유형으로 개방한 ‘고궁2583 덕혜옹주 문항라 부금 당의 ’를 이용하였으며, 해당 저작물은 국립고궁박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.gogung.go.kr/searchView.do?pageIndex=1&cultureSeq=00017518BU&searchRelicDiv4=&searchGubun=ALL1&searchText=%EB%AC%B8%ED%95%AD%EB%9D%BC",
  },
  {
    id: "23",
    imgUrl: "./img/character/list/character-list-thum-23.jpg",
    personUrl: "./img/character/img_person/gogung/02.png",
    kName: "영친왕비 대홍원삼",
    cName: "英親王妃大紅圓衫",
    useColor1: "./img/character/usecolor/gogung/02-1.jpg",
    useColor2: "./img/character/usecolor/gogung/02-2.jpg",
    useColor3: "./img/character/usecolor/gogung/02-3.jpg",
    relicImgUrl: "./img/character/relic/gogung/02.jpg",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText:
      "본 저작물은 국립고궁박물관에서 공공누리 제 1 유형으로 개방한 ‘궁중44 영친왕비 별문숙고사 부금 홍원삼’를 이용하였으며, 해당 저작물은 국립고궁박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.gogung.go.kr/searchView.do?pageIndex=1&cultureSeq=857LJE&searchRelicDiv4=&searchGubun=ALL1&searchText=%EB%8C%80%ED%99%8D%EC%9B%90%EC%82%BC",
  },
  {
    id: "24",
    imgUrl: "./img/character/list/character-list-thum-24.jpg",
    personUrl: "./img/character/img_person/gogung/03.png",
    kName: "이구 별문숙고사 부금 두루마기",
    cName: "李玖別紋熟庫紗付金周衣",
    useColor1: "./img/character/usecolor/gogung/03-1.jpg",
    useColor2: "./img/character/usecolor/gogung/03-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/gogung/03.jpg",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립고궁박물관에서 공공누리 제 1 유형으로 개방한 ‘궁중76 이구 별문숙고사 부금 두루마기’를 이용하였으며, 해당 저작물은 국립고궁박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.gogung.go.kr/searchView.do?pageIndex=3&cultureSeq=887LJE&searchRelicDiv4=&searchGubun=ALL1&searchText=%EB%B3%84%EB%AC%B8%EC%88%99",
  },
  {
    id: "25",
    imgUrl: "./img/character/list/character-list-thum-25.jpg",
    personUrl: "./img/character/img_person/gogung/04.png",
    kName: "후수",
    cName: "後綬",
    useColor1: "./img/character/usecolor/gogung/04-1.jpg",
    useColor2: "./img/character/usecolor/gogung/04-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/gogung/04.jpg",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립고궁박물관에서 공공누리 제 1 유형으로 개방한 ‘창덕23680’를 이용하였으며, 해당 저작물은 국립고궁박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.gogung.go.kr/searchView.do?pageIndex=1&cultureSeq=00020621EH&searchRelicDiv4=&searchGubun=ALL1&searchText=%ED%9B%84%EC%88%98",
  },
  {
    id: "26",
    imgUrl: "./img/character/list/character-list-thum-26.jpg",
    personUrl: "./img/character/img_person/gogung/05.png",
    kName: "유소",
    cName: "流蘇",
    useColor1: "./img/character/usecolor/gogung/05-1.jpg",
    useColor2: "./img/character/usecolor/gogung/05-2.jpg",
    useColor3: "",
    relicImgUrl: "./img/character/relic/gogung/05.jpg",
    copyrightUrl: "./img/character/copyright_img.jpg",
    copyrightText: "본 저작물은 국립고궁박물관에서 공공누리 제 1 유형으로 개방한 ‘창덕 24796’를 이용하였으며, 해당 저작물은 국립고궁박물관에서 무료로 다운받을 수 있습니다.",
    relicUrl: "https://www.gogung.go.kr/searchView.do?pageIndex=41&cultureSeq=00019931IR&searchRelicDiv4=CULD10&searchGubun=ALL1&searchText=",
  },
];
